import StatusLED from "../components/StatusLED.jsx";
import ReadingCard from "../components/ReadingCard.jsx";
import SensorGraph from "../components/SensorGraph.jsx";
import { sensorStatus, statusText } from "../utils/sensorStatus.js";

// ============================================================
// DISPLAY LABELS
// ============================================================
//
// These are UI labels only.
//
// The actual FCAD packet decoding happens in the Python
// Universal Converter. The frontend receives an already-parsed
// JSON object from Subscriber.py.
//
// Bio and Chem definitions are unchanged.
// ============================================================

const labels = {

  // ----------------------------------------------------------
  // BIO
  // ----------------------------------------------------------

  bio: {
    sampleType: "Sample type",
    smallParticleCount: "Small particle count",
    largeParticleCount: "Large particle count",
    smallBiologicalLoad: "Small biological load",
    largeBiologicalLoad: "Large biological load",
    alarm: "Alarm"
  },

  // ----------------------------------------------------------
  // CHEM
  // ----------------------------------------------------------

  chem: {
    date: "Date",
    time: "Time",
    gValue: "G value",
    hValue: "H value",
    mode: "Mode"
  },

  // ----------------------------------------------------------
  // FCAD
  // ----------------------------------------------------------
  //
  // These fields correspond to the FCAD JSON generated by
  // Universal_Convertor.py.
  //
  // IMPORTANT:
  // Do not add fields here until their byte meaning is known.
  // unknownTail is deliberately not displayed.
  // ----------------------------------------------------------

  fcad: {

    // Identification
    sensorName: "Unit name",
    macId: "MAC ID",

    // Main G / H values
    gValue: "G value",
    hValue: "H value",

    // Chemical / RIP values
    gKoChemical: "G chemical Ko",
    hKoChemical: "H chemical Ko",

    koRipG: "Ko RIP G",
    koRipH: "Ko RIP H",

    ripAmpG: "RIP Amp G",
    ripAmpH: "RIP Amp H",

    // Pressure
    atmosphericPressureG: "Atmospheric pressure G",
    atmosphericPressureH: "Atmospheric pressure H",

    gPressure: "G pressure",
    hPressure: "H pressure",

    // Operating information
    hoursRunSinceLastRecharge: "Hours since recharge",
    gDuty: "G duty",
    hDuty: "H duty",

    // Temperature
    bodyTemperature: "Body temperature",
    nozzleTemperature: "Nozzle temperature",

    hvGTemperature: "HV-G temperature",
    hvHTemperature: "HV-H temperature",

    digitalBoardTemperature: "Digital board temperature",
    sensorBoardTemperature: "Sensor board temperature",
    displayBoardTemperature: "Display board temperature",

    // Electrical / flow
    battery: "Battery",
    hvFeedbackG: "HV Feedback G",
    hvFeedbackH: "HV Feedback H",
    flowInOuterLoop: "Flow in outer loop",

    // Status
    valveStatus: "Valve status",
    readyState: "System state",

    // Known values from the documented extended packet
    ko1G: "Ko-1 G",
    ko3H: "Ko-3 H",

    // Packet information
    endPacket: "End packet",
    packetLength: "Packet length"
  }
};


// ============================================================
// VALUE FORMATTERS
// ============================================================
//
// Keeps units readable without changing the actual backend
// values.
//
// The backend sends numeric values. We only format them for
// display here.
// ============================================================

const valueUnits = {

  atmosphericPressureG: " Torr",
  atmosphericPressureH: " Torr",

  gPressure: " Torr",
  hPressure: " Torr",

  bodyTemperature: " °C",
  nozzleTemperature: " °C",

  hvGTemperature: " °C",
  hvHTemperature: " °C",

  digitalBoardTemperature: " °C",
  sensorBoardTemperature: " °C",
  displayBoardTemperature: " °C",

  battery: "%",

  hvFeedbackG: " V",
  hvFeedbackH: " V",

  flowInOuterLoop: "",

  hoursRunSinceLastRecharge: " h",

  gDuty: "",
  hDuty: "",

  koRipG: "",
  koRipH: "",

  ripAmpG: "",
  ripAmpH: "",

  ko1G: "",
  ko3H: ""
};


// ============================================================
// FORMAT FCAD VALUE
// ============================================================

function formatValue(key, value) {

  if (value === undefined || value === null || value === "") {
    return "—";
  }

  // Boolean / strings don't need numeric formatting.
  if (typeof value === "string") {
    return value;
  }

  if (typeof value === "number") {

    // Values already decoded to 2 decimal places.
    if (
      [
        "koRipG",
        "koRipH",
        "ripAmpG",
        "ripAmpH",
        "hvFeedbackG",
        "hvFeedbackH",
        "flowInOuterLoop",
        "ko1G",
        "ko3H"
      ].includes(key)
    ) {
      return `${value.toFixed(2)}${valueUnits[key] || ""}`;
    }

    return `${value}${valueUnits[key] || ""}`;
  }

  return String(value);
}


// ============================================================
// GRAPH DEFINITIONS
// ============================================================
//
// The graph uses values already parsed by the backend.
//
// FCAD:
//   - G pressure
//   - H pressure
//
// These are useful live sensor measurements and correspond
// directly to the values visible in the original FCAD screen.
//
// Other FCAD values are displayed in the reading cards but
// are not plotted yet.
// ============================================================

const graphConfig = {

  bio: [
    {
      key: "smallParticleCount",
      label: "Small particle count",
      color: "#2868d7"
    }
  ],

  chem: [
    {
      key: "gValue",
      label: "G value",
      color: "#2868d7"
    },
    {
      key: "hValue",
      label: "H value",
      color: "#d97b28"
    }
  ],

  fcad: [
  {
    key: "gValue",
    label: "G value",
    color: "#2868d7"
  },
  {
    key: "hValue",
    label: "H value",
    color: "#d97b28"
  }
]
};


// ============================================================
// SENSOR DETAIL PAGE
// ============================================================

export default function SensorDetailPage({
  sensor,
  reading,
  history,
  now
}) {

  const status = sensorStatus(reading, now);

  const typeLabels = labels[sensor.type] || {};

  const config = graphConfig[sensor.type];


  // ==========================================================
  // GRAPH DATA
  // ==========================================================

  const series = config
    ? config.map(line => ({
        ...line,

        points: history.map(item => {

          const value = Number(item.data?.[line.key]);

          return Number.isFinite(value)
            ? value
            : NaN;
        })
      }))
    : [];


  // ==========================================================
  // UI
  // ==========================================================

  return (
    <section className="detail-view">

      {/* ======================================================
          SENSOR LOCATION / TYPE
          ====================================================== */}

      <p className="eyebrow">

        {sensor.location.replaceAll("-", " ")}

        {" · "}

        {sensor.type}

      </p>


      {/* ======================================================
          SENSOR TITLE / STATUS
          ====================================================== */}

      <div className="detail-title-row">

        <h1>{sensor.id}</h1>

        <span className="detail-status">

          <StatusLED color={status} />

          {statusText(status)}

        </span>

      </div>


      {/* ======================================================
          CONNECTION INFORMATION
          ====================================================== */}

      <p className="detail-subline">

        {sensor.ip}:{sensor.port}

        {" · "}

        <span className="topic">
          {sensor.topic}
        </span>

        {" · "}

        {reading
          ? `Last received: ${new Date(
              reading.receivedAt
            ).toLocaleTimeString()}`
          : "No reading received yet"
        }

      </p>


      {/* ======================================================
          FCAD IDENTIFICATION
          ====================================================== */}

      {sensor.type === "fcad" && reading && (

        <div className="reading-grid">

          <ReadingCard
            label="Unit name"
            value={formatValue(
              "sensorName",
              reading.data?.sensorName
            )}
            hasReading={!!reading}
          />

          <ReadingCard
            label="MAC ID"
            value={formatValue(
              "macId",
              reading.data?.macId
            )}
            hasReading={!!reading}
          />

        </div>

      )}


      {/* ======================================================
          READING BOXES
          ====================================================== */}

      <div className="reading-grid">

        {Object.entries(typeLabels)

          // sensorName and macId are already displayed
          // separately for FCAD.
          .filter(([key]) => {

            if (
              sensor.type === "fcad" &&
              (
                key === "sensorName" ||
                key === "macId"
              )
            ) {
              return false;
            }

            return true;
          })

          .map(([key, text]) => {

            const value = reading
              ? formatValue(
                  key,
                  reading.data?.[key]
                )
              : "—";

            return (
              <ReadingCard
                key={key}
                label={text}
                value={value}
                hasReading={!!reading}
              />
            );
          })}

      </div>


      {/* ======================================================
          NO DATA MESSAGE
          ====================================================== */}

      {!reading && (

        <p className="empty-copy">

          Waiting for data from this sensor.
          The boxes above will fill in automatically.

        </p>

      )}


      {/* ======================================================
          LIVE GRAPH
          ====================================================== */}

      {config && (

        <>

          <h2>Live graph</h2>

          <SensorGraph
            series={series}
            yLabel={
              config.length === 1
                ? config[0].label
                : "Value"
            }
          />

        </>

      )}

    </section>
  );
}